import { spawn, type ChildProcess } from 'node:child_process';
import { writeFile, mkdir, access } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { PrinterConfig } from '@printstudio/shared';
import type { Logger } from '../logger.js';

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Manages the go2rtc subprocess that converts Bambu's proprietary TCP camera
 * protocol (port 6000) into browser-friendly WebRTC / MSE streams.
 *
 * Bambu A1 / A1 mini uses a custom source type `bambu://` that go2rtc
 * supports natively — this is why we can't use a generic RTSP client.
 */
export class Go2RtcManager {
  private process: ChildProcess | null = null;
  private readonly binaryPath: string;
  private readonly configPath: string;

  constructor(
    private readonly logger: Logger,
    private readonly port: number,
  ) {
    // Binary lives at apps/bridge/bin/go2rtc (committed to repo).
    this.binaryPath = resolve(HERE, '../../bin/go2rtc');
    // Generated config at apps/bridge/data/go2rtc.yaml (gitignored runtime data).
    this.configPath = resolve(HERE, '../../data/go2rtc.yaml');
  }

  /**
   * Build a go2rtc YAML config from the printer list. Each printer becomes
   * a stream keyed by `printer_<serial>` (serial is safe in URLs).
   */
  private buildConfig(printers: PrinterConfig[]): string {
    const streams = printers
      .filter((p) => p.ipAddress && p.accessCode)
      .map((p) => {
        const key = streamKey(p.serial);
        const url = `bambu://bblp:${p.accessCode}@${p.ipAddress}:6000`;
        return `  ${key}: ${url}`;
      })
      .join('\n');

    return [
      '# Auto-generated by PrintStudio bridge — do not edit manually.',
      'api:',
      `  listen: "127.0.0.1:${this.port}"`,
      '',
      'log:',
      '  level: info',
      '',
      'webrtc:',
      '  candidates:',
      '    - 127.0.0.1:8555',
      '',
      'streams:',
      streams || '  # no printers configured',
      '',
    ].join('\n');
  }

  async start(printers: PrinterConfig[]): Promise<void> {
    try {
      await access(this.binaryPath);
    } catch {
      this.logger.warn(
        { binary: this.binaryPath },
        'go2rtc binary not found — camera streams disabled',
      );
      return;
    }

    await mkdir(dirname(this.configPath), { recursive: true });
    await writeFile(this.configPath, this.buildConfig(printers), 'utf-8');
    this.logger.info({ configPath: this.configPath, port: this.port }, 'go2rtc starting');

    this.process = spawn(this.binaryPath, ['-config', this.configPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    this.process.stdout?.on('data', (chunk: Buffer) => {
      const line = chunk.toString('utf-8').trim();
      if (line) this.logger.debug({ go2rtc: line.slice(0, 300) }, 'go2rtc stdout');
    });
    this.process.stderr?.on('data', (chunk: Buffer) => {
      const line = chunk.toString('utf-8').trim();
      if (line) this.logger.warn({ go2rtc: line.slice(0, 300) }, 'go2rtc stderr');
    });

    this.process.on('exit', (code, signal) => {
      this.logger.warn({ code, signal }, 'go2rtc exited');
      this.process = null;
    });
  }

  stop(): void {
    if (this.process) {
      this.process.removeAllListeners('exit');
      this.process.kill('SIGTERM');
      this.process = null;
    }
  }

  isRunning(): boolean {
    return this.process !== null && !this.process.killed;
  }
}

export function streamKey(serial: string): string {
  return `printer_${serial.toLowerCase()}`;
}
